FROM node:22-alpine AS build
WORKDIR /app

RUN apk add --no-cache python3 make g++

RUN corepack enable

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 1337


CMD ["sh", "-c", "node scripts/seed && npm run start"]