FROM node:22-alpine AS build
WORKDIR /app

RUN corepack enable

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=3000

EXPOSE 3000


CMD ["node", ".output/server/index.mjs"]